### ISSUE TITLE
Ideas for changes in the internal structure

### ISSUE THREAD

**Issue by hamogu** [taldcroft/asciitable#17]
Just some small ideas to simplify things in asciitable. This post does not mean that I offer to implement that soon, I just want to make sure these things do not get lost.
- `formatter` and `converter` really do the same thing, one for input, one for output. That could be unified.
- `MemoryReader` should recognize numpy masked arrays and use the mask in some way on output. After all, masked arrays are the default output, if a table is read with `fill_values`.
- `Outputter` as a class are only used when reading a table, maybe we should use the same structure for writing.

**Comment by taldcroft** [comment]
Active development will continue with `astropy.io.ascii`.  Transferring (in slightly modified form) to an issue there.
