### ISSUE TITLE
How to produce fixed with output

### ISSUE THREAD

**Issue by ghost** [taldcroft/asciitable#21]
Hello. asciimodule looks very nice, but I am somewhat unsure about the best way to produce output tables with a fixed-width format.

To clarify, I would like to create a table which look like this:

```
| col1 | very_long_column_2 |     col3 |
|  2.2 |                  0 |          |
|    1 |                1.1 | 1.111111 |
```

The code I tried writing to do this is

```
import asciitable
import sys

table = {'col1': [2.2,1],
        'very_long_column_2': [0,1.1],
        'col3': ['', 1.11111]}

writer=asciitable.get_writer(
                 delimiter='|',
                )

fixed=asciitable.core.FixedWidthSplitter
writer.data.splitter_class = fixed
writer.data.splitter = fixed()
writer.header.splitter_class = fixed
writer.header.splitter = fixed()

reader = asciitable.get_reader(Reader=asciitable.memory.Memory)
reader.read(table)

print '\n'.join(writer.write(reader))
```

But the output is not very good

```
col1 col3 very_long_column_2
2.2  0
1 1.11111 1.1
```

Is the a correct way to obtain the desired output using asciitable?

All the best,

**Comment by taldcroft** [comment]
Unfortunately there is no generic FixedWidth reader and writer in asciitable now so you cannot easily use asciitable to output such a table.  This is a good idea and one that I'll keep open as a desired enhancement.  In the meantime it is just a few lines of code to generate the fixed width output:

```
delimiter = '|'
formats = {}
for col in reader.cols:
    formats[col.name] = '%%%ds' % max(len(col.name), max(len(str(x)) for x in col.data))

null = ['']
print delimiter.join(null +
                     [formats[col.name] % col.name for col in reader.cols] +
                     null)
for row in reader.table:
    print delimiter.join(null +
                         [formats[col.name] % row[col.name] for col in reader.cols] + 
                         null)
```

**Comment by ghost** [comment]
Thank you for your quick reply. 

In my experince, fixed width tables are used very commonly at my work since they are the simplest format to read. And also, we use internally the confluence wiki system which looks for tables in the above format. So having a dead simple python module to read and write these tables would be very useful.

As a followup question (or request), is there a simpler way of appending the delimiter to the beginning and end of each row. For some delimiters, like tabs, this is not useful. But for other delimiters, like '|', this makes the table easier to read (and is required by confluence). It looks like your example requires adding a new blank column to the beginning and end of the table, which is a little bit cumbersome.

And finally, is there any though of supporting delimeters with more than one charater? I would prefer to have a delimiter that was like ' | ' with two spaces on either side, but currently the code crashes when I request this.

Thanks again for your help

**Comment by taldcroft** [comment]
Having a way to deal with "hanging delimiters" in a simpler way would be useful and it's something I've had trouble with myself.  So the idea might be to introduce an end_delimiter keyword that would work for reading (by stripping it) and writing (by adding it on both ends).  Need to think about the cleanest way to do this so it works for all basic tables.

The limitation on the delimiter being one character comes from the Python csv.writer standard library method that is used to join table column values.  This is a convenient library to use because it handles quoting and escaping special characters.  I probably won't replace that routine just to get multi-character delimiters.  However, asciitable is modular and you can override the writer.data.splitter.join method with your own simple routine to just use the simple Python join() method (and forget about quoting and special characters).

**Comment by taldcroft** [comment]
Started work on FixedWidth reader / writer class in new fixedwidth branch.  Simple reads work, still needs plenty of work.

**Comment by ghost** [comment]
That is great! I think this feature will be of great use. When you think the code is stable enough, I will be happy to check it out and test it.

**Comment by taldcroft** [comment]
@deduBas8  - If you have some examples of fixed width files that you'd like to be able to read that would be helpful.  Just the header and first few data lines.  You could put this in a gist for example.

**Comment by ghost** [comment]
Hi taldcroft.

I am most interested in loading my tables into the confluence wiki system, so I have attached an example table from the confluence help.

https://gist.github.com/1251066

Note that this wiki engine also accepts tables where the delimiter of the first line is '||'. I don't know if this would be substantially more difficult to incorporate.

**Comment by ghost** [comment]
Here is another example of a fixed width table that I have to use at work.

http://fermi.gsfc.nasa.gov/ssc/data/analysis/software/aux/iso_p7v6source.txt

All the best,

**Comment by ghost** [comment]
Here is another fixed with table

https://gist.github.com/1251101

**Comment by taldcroft** [comment]
FixedWidth read and write functionality completed, ready for testing.

Please check out the fixedwidth branch or the dev tarball:
 https://github.com/taldcroft/asciitable/tree/fixedwidth
 http://cxc.harvard.edu/contrib/asciitable/dev/downloads/asciitable.tar.gz

Docs at:
 http://cxc.harvard.edu/contrib/asciitable/dev/fixed_width_gallery.html

**Comment by ghost** [comment]
Wow. This is really an amazing contribution and way more then I could have possibly hoped for. I will make sure to give your new code a very through testing and also recommend your very nice module to others.

Aa quick question: is there an easy way to write out the table to have the same format as the table from the section "Table with double delimiters"? If so, it might be nice to add an example of this to the documentation.

Again, thank you so much for all your hard work

**Comment by ghost** [comment]
My Preliminary testing has been very successful. This new code is quite an improvement!

**Comment by taldcroft** [comment]
Release 0.8.0 closes this.  :-)

**Comment by ghost** [comment]
Thank you so much for this very nice feature. It is very much appreciated.
