### ISSUE TITLE
tests fail for the latex writer

### ISSUE THREAD

**Issue by saimn** [taldcroft/asciitable#27]
While running tests, I noticed that 4 tests are failing in `test/test_write.py` with the latex writer. This is due to an extra line in the output of the writer : 

```
  &   &   &   &   &   &   &   &   &   &   \\
```

This line should contains the units (feature added with PR #24) but in this case it seems that no units are provided.

**Comment by taldcroft** [comment]
Added the required line so the tests pass in e8958bdb72.  Based on the discussion from the original author in PR #24 this is the desired and correct behavior.
